trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'src/NaturalLangugeTools.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet --version
- script: dotnet build --configuration $(buildConfiguration) $(solution)
- script: dotnet test --logger trx --collect "Code coverage" $(solution)
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
