trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'src/NaturalLangugeTools.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet --version
- script: ls ; dotnet build --configuration $(buildConfiguration) '$(solution)'
- script: dotnet test '$(solution)' --logger trx --collect "Code coverage"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
