trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'src/NaturalLangugeTools.sln'
  buildConfiguration: 'Release'

steps:
- powershell: dotnet --version
  displayName: .NET Core Version

- script: dotnet build --configuration $(buildConfiguration) $(solution)
  displayName: Build the project

- script: dotnet test --logger trx --collect "Code coverage" $(solution)
  displayName: Run the tests

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
